apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: expenses-microservice
resources:
  - deployment.yml
  - service.yml
images:
  - name: gcr.io/dev-ops-264603/expenses-microservice
    newTag: latest
