apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: expenses-microservice
resources:
  - deployment.yml
  - service.yml
images:
  - name: docker.pkg.github.com/blossombudgeting/expenses-microservice/expenses-microservice
    newTag: latest