---
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://mongosrvdev:ZxuF9TxpDae5dGT@dev-gngtd.azure.mongodb.net/blossom?retryWrites=true&w=majority}
springdoc:
  swagger-ui:
    path: /expenses/swagger-ui.html
  api-docs:
    path: /expenses/v3/api-docs