name: Build and Deploy to PCF Dev

on:
  push:
    branches:
      - dev
env:
  CF_USERNAME: ${{ secrets.CF_USERNAME }}
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
  CF_TARGET_ORG: Blossom Budgeting
  CF_TARGET_SPACE: dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: CF Deploy
        uses: citizen-of-planet-earth/cf-cli-action@v1
        with:
          cf_username: $CF_USERNAME
          cf_password: $CF_PASSWORD
          cf_org: $CF_TARGET_ORG
          # Target Space
          cf_space: $CF_TARGET_SPACE
          # Command to run using CF CLI
          command: push